name = "tiffany-mcp"
main = "tiffany-mcp-compliant.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "production"

# MCP Server requires these for proper operation
[build]
command = ""

# Secrets to be set via wrangler secret put
# wrangler secret put OPENROUTER_API_KEY
# wrangler secret put AIRTABLE_API_KEY
# wrangler secret put AIRTABLE_BASE_ID

# Rate limiting and performance
[limits]
cpu_ms = 50

# Custom domain after deployment
[[routes]]
pattern = "tiffany-mcp.danielmiessler.workers.dev/*"
zone_name = "danielmiessler.workers.dev"