name = "tiffany-mcp"
main = "tiffany-mcp.js"
compatibility_date = "2024-01-01"

# Environment variables (set via wrangler secret put)
[vars]
ENVIRONMENT = "production"

# Add secrets using:
# wrangler secret put OPENROUTER_API_KEY
# wrangler secret put AIRTABLE_API_KEY
# wrangler secret put AIRTABLE_BASE_ID

[build]
command = ""

# Rate limiting
[limits]
cpu_ms = 50

# Custom domain (update after deployment)
[[routes]]
pattern = "tiffany-mcp.danielmiessler.workers.dev/*"
zone_name = "danielmiessler.workers.dev"