name = "tiffany-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Enable Node.js compatibility for MCP SDK
compatibility_flags = ["nodejs_compat_v2"]

# Allow access from all origins for MCP clients
[env.production]
# Production environment settings can be added here

# Development environment
[env.staging]
# Staging environment settings can be added here

# CORS configuration for MCP client access
[vars]
ENVIRONMENT = "production"

# Optional: Smart placement for optimal performance
[placement]
mode = "smart"

# Durable Objects configuration for MCP Agent
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"