name = "tiffany-mcp-server"
compatibility_date = "2024-11-01"
main = "src/index.ts"

[env.production]
name = "tiffany-mcp-official"

# Environment variables (will be set via Cloudflare dashboard or CLI)
[vars]
# These will be populated from your .env file during deployment

# Secrets (set via: wrangler secret put SECRET_NAME)
# AIRTABLE_API_KEY - Set via CLI: wrangler secret put AIRTABLE_API_KEY
# AIRTABLE_BASE_ID - Set via CLI: wrangler secret put AIRTABLE_BASE_ID  
# OPENAI_API_KEY - Set via CLI: wrangler secret put OPENAI_API_KEY
# OPENROUTER_API_KEY - Set via CLI: wrangler secret put OPENROUTER_API_KEY
# TELEGRAM_BOT_TOKEN_TIFFANY - Set via CLI: wrangler secret put TELEGRAM_BOT_TOKEN_TIFFANY

# Durable Objects for persistent state
[[durable_objects.bindings]]
name = "TIFFANY_STATE"
class_name = "TiffanyDurableObject"

# KV for caching (optional)
[[kv_namespaces]]
binding = "TIFFANY_CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# Node.js compatibility for MCP SDK and crypto operations
node_compat = true

# Build configuration
[build]
command = "npm run build"

# Development configuration  
[env.development]
name = "tiffany-mcp-dev"
